name: .NET WASM CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Run tests with coverage
      run: |
        dotnet test --no-restore --collect:"XPlat Code Coverage" \
        /p:CoverletOutputFormat=cobertura

    - name: List coverage report files
      run: ls -R coveragereport

    - name: Generate and check coverage report
      run: |
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport
        if [ -f coveragereport/cobertura/cobertura.xml ]; then
          coverage=$(grep -oP '(?<=line-rate=\")[^\"]+' coveragereport/cobertura/cobertura.xml | awk '{total += $1; count++} END {print total/count}')
          if [ -z "$coverage" ]; then
            echo "No coverage data found."
            exit 1
          else
            echo "Coverage: $coverage"
            if (( $(echo "$coverage < 0.80" | bc -l) )); then
              echo "Code coverage is below 80%. Failing the build."
              exit 1
            fi
          fi
        else
          echo "Coverage file not found. Failing the build."
          exit 1
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coveragereport