name: .NET WASM CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Run tests with coverage
      run: |
        dotnet test --no-restore --collect:"XPlat Code Coverage" \
        /p:CoverletOutputFormat=cobertura

    - name: List TestResults Directory
      run: |
        ls -R ./CSharpCodeReviewNUnitTest/TestResults

    - name: Check coverage
      run: |
        coverage_file=$(find . -name "coverage.cobertura.xml")
        if [ -f "$coverage_file" ]; then
          coverage=$(grep -oP '(?<=line-rate=\")[^\"]+' "$coverage_file" | awk '{total += $1; count++} END {print total/count}')
          echo "Coverage: $coverage"
          if (( $(echo "$coverage < 0.80" | bc -l) )); then
            echo "Code coverage is below 80%. Failing the build."
            exit 1
          fi
        else
          echo "Coverage file not found. Failing the build."
          exit 1
        fi

    - name: Install GitHub CLI
      if: always()
      run: sudo apt-get install gh
  
    - name: Post a comment to PR if coverage is below 80%
      if: failure() && github.event_name == 'pull_request'
      env:
          GITHUB_TOKEN: ${{ secrets.G_AUTO_TOKEN }}
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **Code Coverage Alert** ⚠️ Your current code coverage is **${{ steps.check_coverage.outputs.coverage }}**. 
        Unfortunately, it's below the required threshold of **80%**.
        Please review the tests and add more coverage to ensure the quality of the codebase.
        Remember, maintaining good code coverage helps to prevent bugs and improves the reliability of the code!"